# Generated by Django 4.0.6 on 2022-07-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='3d id')),
                ('data', models.JSONField(verbose_name='3d model data')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='home bage id')),
                ('logo', models.ImageField(upload_to='')),
                ('model_3d', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.model3d')),
            ],
        ),
    ]
