# Generated by Django 4.0.6 on 2022-07-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeBage',
            new_name='HomeBages',
        ),
        migrations.RenameModel(
            old_name='Model3D',
            new_name='Model3Ds',
        ),
        migrations.AlterModelTable(
            name='homebages',
            table='homebages',
        ),
        migrations.AlterModelTable(
            name='model3ds',
            table='model3ds',
        ),
    ]
